services:
  web:
    build: .

    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - db-data:/app

    ports:
      - "8000:8000"

    env_file:
      - .env

volumes:
  db-data:
