# Generated by Django 5.2.6 on 2025-09-29 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excercise',
            name='instructions',
        ),
    ]
