# Generated by Django 5.2.6 on 2025-09-29 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0002_remove_excercise_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_exercises', to='workout_api.excercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workout_api.workoutsession'),
        ),
    ]
