# Generated by Django 5.2.6 on 2025-09-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0004_workoutsession_start_time_progresstracker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracker',
            name='goal_type',
            field=models.CharField(choices=[('weight', 'Weight'), ('exercise', 'Eexercise')], max_length=50),
        ),
    ]
