# Generated by Django 5.2.6 on 2025-09-30 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0005_alter_progresstracker_goal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresstracker',
            name='current_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
